// This file was auto-generated by ML.NET Model Builder. 

using System;
using EjercicioEvaluacionAgropecuariaML.Model;

namespace EjercicioEvaluacionAgropecuariaML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                EDAD = @"39",
                PS82A = 60.2F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual PS84 with predicted PS84 from sample data...\n\n");
            Console.WriteLine($"EDAD: {sampleData.EDAD}");
            Console.WriteLine($"PS82A: {sampleData.PS82A}");
            Console.WriteLine($"\n\nPredicted PS84: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
