// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace EjercicioEvaluacionAgropecuariaML.Model
{
    public class ModelInput
    {
        [ColumnName("IDENTIF_SECT"), LoadColumn(0)]
        public float IDENTIF_SECT { get; set; }


        [ColumnName("IDENTIF_HOG"), LoadColumn(1)]
        public float IDENTIF_HOG { get; set; }


        [ColumnName("AREA_5000"), LoadColumn(2)]
        public string AREA_5000 { get; set; }


        [ColumnName("AREA_2000"), LoadColumn(3)]
        public string AREA_2000 { get; set; }


        [ColumnName("CIUDAD_AUTO"), LoadColumn(4)]
        public string CIUDAD_AUTO { get; set; }


        [ColumnName("PROVINCIA"), LoadColumn(5)]
        public string PROVINCIA { get; set; }


        [ColumnName("ZDP"), LoadColumn(6)]
        public string ZDP { get; set; }


        [ColumnName("REGION"), LoadColumn(7)]
        public string REGION { get; set; }


        [ColumnName("CIUDAD"), LoadColumn(8)]
        public float CIUDAD { get; set; }


        [ColumnName("ZONA"), LoadColumn(9)]
        public float ZONA { get; set; }


        [ColumnName("SECTOR"), LoadColumn(10)]
        public float SECTOR { get; set; }


        [ColumnName("VIVIENDA"), LoadColumn(11)]
        public float VIVIENDA { get; set; }


        [ColumnName("HOGAR"), LoadColumn(12)]
        public float HOGAR { get; set; }


        [ColumnName("PERIODO"), LoadColumn(13)]
        public string PERIODO { get; set; }


        [ColumnName("PERSONA"), LoadColumn(14)]
        public float PERSONA { get; set; }


        [ColumnName("SEXO"), LoadColumn(15)]
        public string SEXO { get; set; }


        [ColumnName("EDAD"), LoadColumn(16)]
        public string EDAD { get; set; }


        [ColumnName("PD03B"), LoadColumn(17)]
        public float PD03B { get; set; }


        [ColumnName("PD04"), LoadColumn(18)]
        public string PD04 { get; set; }


        [ColumnName("PD05"), LoadColumn(19)]
        public string PD05 { get; set; }


        [ColumnName("PD06"), LoadColumn(20)]
        public string PD06 { get; set; }


        [ColumnName("PD07"), LoadColumn(21)]
        public string PD07 { get; set; }


        [ColumnName("PD08A"), LoadColumn(22)]
        public string PD08A { get; set; }


        [ColumnName("PD08B"), LoadColumn(23)]
        public string PD08B { get; set; }


        [ColumnName("PD08C"), LoadColumn(24)]
        public string PD08C { get; set; }


        [ColumnName("PD08D"), LoadColumn(25)]
        public string PD08D { get; set; }


        [ColumnName("PD08E"), LoadColumn(26)]
        public string PD08E { get; set; }


        [ColumnName("PD09"), LoadColumn(27)]
        public string PD09 { get; set; }


        [ColumnName("PD10A"), LoadColumn(28)]
        public string PD10A { get; set; }


        [ColumnName("PD10B"), LoadColumn(29)]
        public float PD10B { get; set; }


        [ColumnName("PD11"), LoadColumn(30)]
        public string PD11 { get; set; }


        [ColumnName("PD12"), LoadColumn(31)]
        public float PD12 { get; set; }


        [ColumnName("PD13"), LoadColumn(32)]
        public string PD13 { get; set; }


        [ColumnName("PD14A"), LoadColumn(33)]
        public string PD14A { get; set; }


        [ColumnName("PD14B"), LoadColumn(34)]
        public string PD14B { get; set; }


        [ColumnName("PD14C"), LoadColumn(35)]
        public string PD14C { get; set; }


        [ColumnName("PD14D"), LoadColumn(36)]
        public string PD14D { get; set; }


        [ColumnName("PD14E"), LoadColumn(37)]
        public string PD14E { get; set; }


        [ColumnName("PD14F"), LoadColumn(38)]
        public string PD14F { get; set; }


        [ColumnName("PD14G"), LoadColumn(39)]
        public string PD14G { get; set; }


        [ColumnName("PD14H"), LoadColumn(40)]
        public string PD14H { get; set; }


        [ColumnName("PD15A"), LoadColumn(41)]
        public string PD15A { get; set; }


        [ColumnName("PD15B"), LoadColumn(42)]
        public float PD15B { get; set; }


        [ColumnName("PD15C"), LoadColumn(43)]
        public float PD15C { get; set; }


        [ColumnName("PD16"), LoadColumn(44)]
        public string PD16 { get; set; }


        [ColumnName("PD17A"), LoadColumn(45)]
        public string PD17A { get; set; }


        [ColumnName("PD17B"), LoadColumn(46)]
        public float PD17B { get; set; }


        [ColumnName("PD17C"), LoadColumn(47)]
        public float PD17C { get; set; }


        [ColumnName("PD18"), LoadColumn(48)]
        public string PD18 { get; set; }


        [ColumnName("PD19"), LoadColumn(49)]
        public string PD19 { get; set; }


        [ColumnName("PD20A"), LoadColumn(50)]
        public string PD20A { get; set; }


        [ColumnName("PD20B"), LoadColumn(51)]
        public float PD20B { get; set; }


        [ColumnName("PD21A"), LoadColumn(52)]
        public string PD21A { get; set; }


        [ColumnName("PD21B"), LoadColumn(53)]
        public float PD21B { get; set; }


        [ColumnName("PD22A"), LoadColumn(54)]
        public string PD22A { get; set; }


        [ColumnName("PD22B"), LoadColumn(55)]
        public string PD22B { get; set; }


        [ColumnName("PD23"), LoadColumn(56)]
        public string PD23 { get; set; }


        [ColumnName("PD24A"), LoadColumn(57)]
        public string PD24A { get; set; }


        [ColumnName("PD24B"), LoadColumn(58)]
        public float PD24B { get; set; }


        [ColumnName("PD25A"), LoadColumn(59)]
        public string PD25A { get; set; }


        [ColumnName("PD25B"), LoadColumn(60)]
        public float PD25B { get; set; }


        [ColumnName("PD26"), LoadColumn(61)]
        public string PD26 { get; set; }


        [ColumnName("PS01"), LoadColumn(62)]
        public string PS01 { get; set; }


        [ColumnName("PS02"), LoadColumn(63)]
        public string PS02 { get; set; }


        [ColumnName("PS03A"), LoadColumn(64)]
        public float PS03A { get; set; }


        [ColumnName("PS03B"), LoadColumn(65)]
        public float PS03B { get; set; }


        [ColumnName("PS04"), LoadColumn(66)]
        public string PS04 { get; set; }


        [ColumnName("PS05"), LoadColumn(67)]
        public string PS05 { get; set; }


        [ColumnName("PS06"), LoadColumn(68)]
        public string PS06 { get; set; }


        [ColumnName("PS07A"), LoadColumn(69)]
        public string PS07A { get; set; }


        [ColumnName("PS07B"), LoadColumn(70)]
        public string PS07B { get; set; }


        [ColumnName("PS08"), LoadColumn(71)]
        public string PS08 { get; set; }


        [ColumnName("PS09A"), LoadColumn(72)]
        public string PS09A { get; set; }


        [ColumnName("PS09B"), LoadColumn(73)]
        public string PS09B { get; set; }


        [ColumnName("PS10A"), LoadColumn(74)]
        public string PS10A { get; set; }


        [ColumnName("PS10B"), LoadColumn(75)]
        public string PS10B { get; set; }


        [ColumnName("PS11"), LoadColumn(76)]
        public string PS11 { get; set; }


        [ColumnName("PS12A"), LoadColumn(77)]
        public string PS12A { get; set; }


        [ColumnName("PS12B"), LoadColumn(78)]
        public float PS12B { get; set; }


        [ColumnName("PS13A"), LoadColumn(79)]
        public string PS13A { get; set; }


        [ColumnName("PS13B"), LoadColumn(80)]
        public float PS13B { get; set; }


        [ColumnName("PS13C"), LoadColumn(81)]
        public string PS13C { get; set; }


        [ColumnName("PS14A"), LoadColumn(82)]
        public string PS14A { get; set; }


        [ColumnName("PS14B"), LoadColumn(83)]
        public float PS14B { get; set; }


        [ColumnName("PS15"), LoadColumn(84)]
        public string PS15 { get; set; }


        [ColumnName("PS16A"), LoadColumn(85)]
        public string PS16A { get; set; }


        [ColumnName("PS16B"), LoadColumn(86)]
        public float PS16B { get; set; }


        [ColumnName("PS17"), LoadColumn(87)]
        public string PS17 { get; set; }


        [ColumnName("PS18"), LoadColumn(88)]
        public string PS18 { get; set; }


        [ColumnName("PS19"), LoadColumn(89)]
        public string PS19 { get; set; }


        [ColumnName("PS20"), LoadColumn(90)]
        public string PS20 { get; set; }


        [ColumnName("PS21"), LoadColumn(91)]
        public string PS21 { get; set; }


        [ColumnName("PS22"), LoadColumn(92)]
        public string PS22 { get; set; }


        [ColumnName("PS23A"), LoadColumn(93)]
        public string PS23A { get; set; }


        [ColumnName("PS23B"), LoadColumn(94)]
        public string PS23B { get; set; }


        [ColumnName("PS24"), LoadColumn(95)]
        public string PS24 { get; set; }


        [ColumnName("PS25"), LoadColumn(96)]
        public string PS25 { get; set; }


        [ColumnName("PS26"), LoadColumn(97)]
        public string PS26 { get; set; }


        [ColumnName("PS27"), LoadColumn(98)]
        public string PS27 { get; set; }


        [ColumnName("PS28"), LoadColumn(99)]
        public string PS28 { get; set; }


        [ColumnName("PS29A"), LoadColumn(100)]
        public string PS29A { get; set; }


        [ColumnName("PS29B"), LoadColumn(101)]
        public string PS29B { get; set; }


        [ColumnName("PS30"), LoadColumn(102)]
        public string PS30 { get; set; }


        [ColumnName("PS31"), LoadColumn(103)]
        public string PS31 { get; set; }


        [ColumnName("PS32A"), LoadColumn(104)]
        public string PS32A { get; set; }


        [ColumnName("PS32B"), LoadColumn(105)]
        public string PS32B { get; set; }


        [ColumnName("PS33"), LoadColumn(106)]
        public string PS33 { get; set; }


        [ColumnName("PS34"), LoadColumn(107)]
        public string PS34 { get; set; }


        [ColumnName("PS35"), LoadColumn(108)]
        public string PS35 { get; set; }


        [ColumnName("PS36"), LoadColumn(109)]
        public string PS36 { get; set; }


        [ColumnName("PS37"), LoadColumn(110)]
        public string PS37 { get; set; }


        [ColumnName("PS38"), LoadColumn(111)]
        public string PS38 { get; set; }


        [ColumnName("PS39"), LoadColumn(112)]
        public string PS39 { get; set; }


        [ColumnName("PS40A"), LoadColumn(113)]
        public float PS40A { get; set; }


        [ColumnName("PS40B"), LoadColumn(114)]
        public float PS40B { get; set; }


        [ColumnName("PS41A"), LoadColumn(115)]
        public float PS41A { get; set; }


        [ColumnName("PS41B"), LoadColumn(116)]
        public float PS41B { get; set; }


        [ColumnName("PS42"), LoadColumn(117)]
        public string PS42 { get; set; }


        [ColumnName("PS43"), LoadColumn(118)]
        public string PS43 { get; set; }


        [ColumnName("PS44A"), LoadColumn(119)]
        public string PS44A { get; set; }


        [ColumnName("PS44B"), LoadColumn(120)]
        public string PS44B { get; set; }


        [ColumnName("PS45"), LoadColumn(121)]
        public string PS45 { get; set; }


        [ColumnName("PS46"), LoadColumn(122)]
        public string PS46 { get; set; }


        [ColumnName("PS47"), LoadColumn(123)]
        public string PS47 { get; set; }


        [ColumnName("PS48"), LoadColumn(124)]
        public string PS48 { get; set; }


        [ColumnName("PS49"), LoadColumn(125)]
        public string PS49 { get; set; }


        [ColumnName("PS50"), LoadColumn(126)]
        public string PS50 { get; set; }


        [ColumnName("PS51A"), LoadColumn(127)]
        public float PS51A { get; set; }


        [ColumnName("PS51B"), LoadColumn(128)]
        public float PS51B { get; set; }


        [ColumnName("PS52A"), LoadColumn(129)]
        public float PS52A { get; set; }


        [ColumnName("PS52B"), LoadColumn(130)]
        public float PS52B { get; set; }


        [ColumnName("PS53"), LoadColumn(131)]
        public string PS53 { get; set; }


        [ColumnName("PS54"), LoadColumn(132)]
        public string PS54 { get; set; }


        [ColumnName("PS55A"), LoadColumn(133)]
        public string PS55A { get; set; }


        [ColumnName("PS55B"), LoadColumn(134)]
        public string PS55B { get; set; }


        [ColumnName("PS56"), LoadColumn(135)]
        public string PS56 { get; set; }


        [ColumnName("PS57"), LoadColumn(136)]
        public string PS57 { get; set; }


        [ColumnName("PS58"), LoadColumn(137)]
        public string PS58 { get; set; }


        [ColumnName("PS59A"), LoadColumn(138)]
        public string PS59A { get; set; }


        [ColumnName("PS59B"), LoadColumn(139)]
        public string PS59B { get; set; }


        [ColumnName("PS60A"), LoadColumn(140)]
        public string PS60A { get; set; }


        [ColumnName("PS60B"), LoadColumn(141)]
        public float PS60B { get; set; }


        [ColumnName("PS61"), LoadColumn(142)]
        public string PS61 { get; set; }


        [ColumnName("PS62"), LoadColumn(143)]
        public string PS62 { get; set; }


        [ColumnName("PS63"), LoadColumn(144)]
        public string PS63 { get; set; }


        [ColumnName("PS64"), LoadColumn(145)]
        public string PS64 { get; set; }


        [ColumnName("PS65"), LoadColumn(146)]
        public string PS65 { get; set; }


        [ColumnName("PS66"), LoadColumn(147)]
        public string PS66 { get; set; }


        [ColumnName("PS67A"), LoadColumn(148)]
        public float PS67A { get; set; }


        [ColumnName("PS67B"), LoadColumn(149)]
        public float PS67B { get; set; }


        [ColumnName("PS68A"), LoadColumn(150)]
        public float PS68A { get; set; }


        [ColumnName("PS68B"), LoadColumn(151)]
        public float PS68B { get; set; }


        [ColumnName("PS69"), LoadColumn(152)]
        public string PS69 { get; set; }


        [ColumnName("PS70"), LoadColumn(153)]
        public string PS70 { get; set; }


        [ColumnName("PS71A"), LoadColumn(154)]
        public string PS71A { get; set; }


        [ColumnName("PS71B"), LoadColumn(155)]
        public string PS71B { get; set; }


        [ColumnName("PS72A"), LoadColumn(156)]
        public string PS72A { get; set; }


        [ColumnName("PS72B"), LoadColumn(157)]
        public string PS72B { get; set; }


        [ColumnName("PS73"), LoadColumn(158)]
        public string PS73 { get; set; }


        [ColumnName("PS74"), LoadColumn(159)]
        public string PS74 { get; set; }


        [ColumnName("PS74AA"), LoadColumn(160)]
        public string PS74AA { get; set; }


        [ColumnName("PS74AB"), LoadColumn(161)]
        public string PS74AB { get; set; }


        [ColumnName("PS74AC"), LoadColumn(162)]
        public string PS74AC { get; set; }


        [ColumnName("PS74AD"), LoadColumn(163)]
        public string PS74AD { get; set; }


        [ColumnName("PS74AE"), LoadColumn(164)]
        public string PS74AE { get; set; }


        [ColumnName("PS74AF"), LoadColumn(165)]
        public string PS74AF { get; set; }


        [ColumnName("PS75"), LoadColumn(166)]
        public string PS75 { get; set; }


        [ColumnName("PS76"), LoadColumn(167)]
        public string PS76 { get; set; }


        [ColumnName("PS77A"), LoadColumn(168)]
        public string PS77A { get; set; }


        [ColumnName("PS77B"), LoadColumn(169)]
        public string PS77B { get; set; }


        [ColumnName("PS77C"), LoadColumn(170)]
        public string PS77C { get; set; }


        [ColumnName("PS77D"), LoadColumn(171)]
        public string PS77D { get; set; }


        [ColumnName("PS77E"), LoadColumn(172)]
        public string PS77E { get; set; }


        [ColumnName("PS77F"), LoadColumn(173)]
        public string PS77F { get; set; }


        [ColumnName("PS77G"), LoadColumn(174)]
        public string PS77G { get; set; }


        [ColumnName("PS77H"), LoadColumn(175)]
        public string PS77H { get; set; }


        [ColumnName("PS78A"), LoadColumn(176)]
        public string PS78A { get; set; }


        [ColumnName("PS78B"), LoadColumn(177)]
        public string PS78B { get; set; }


        [ColumnName("PS78C"), LoadColumn(178)]
        public string PS78C { get; set; }


        [ColumnName("PS79"), LoadColumn(179)]
        public string PS79 { get; set; }


        [ColumnName("PS80A"), LoadColumn(180)]
        public string PS80A { get; set; }


        [ColumnName("PS80B"), LoadColumn(181)]
        public string PS80B { get; set; }


        [ColumnName("PS80C"), LoadColumn(182)]
        public string PS80C { get; set; }


        [ColumnName("PS81A"), LoadColumn(183)]
        public float PS81A { get; set; }


        [ColumnName("PS81B"), LoadColumn(184)]
        public float PS81B { get; set; }


        [ColumnName("PS81C"), LoadColumn(185)]
        public float PS81C { get; set; }


        [ColumnName("PS82"), LoadColumn(186)]
        public float PS82 { get; set; }


        [ColumnName("PS82A"), LoadColumn(187)]
        public float PS82A { get; set; }


        [ColumnName("PS82B"), LoadColumn(188)]
        public float PS82B { get; set; }


        [ColumnName("PS83"), LoadColumn(189)]
        public float PS83 { get; set; }


        [ColumnName("PS83A"), LoadColumn(190)]
        public float PS83A { get; set; }


        [ColumnName("PS83B"), LoadColumn(191)]
        public float PS83B { get; set; }


        [ColumnName("PS84"), LoadColumn(192)]
        public float PS84 { get; set; }


        [ColumnName("PS84A"), LoadColumn(193)]
        public float PS84A { get; set; }


        [ColumnName("PS84B"), LoadColumn(194)]
        public float PS84B { get; set; }


        [ColumnName("PS85"), LoadColumn(195)]
        public string PS85 { get; set; }


        [ColumnName("PH01A"), LoadColumn(196)]
        public string PH01A { get; set; }


        [ColumnName("PH01B"), LoadColumn(197)]
        public float PH01B { get; set; }


        [ColumnName("PH01C"), LoadColumn(198)]
        public float PH01C { get; set; }


        [ColumnName("PH02A"), LoadColumn(199)]
        public string PH02A { get; set; }


        [ColumnName("PH02B"), LoadColumn(200)]
        public string PH02B { get; set; }


        [ColumnName("PH02C"), LoadColumn(201)]
        public string PH02C { get; set; }


        [ColumnName("PH02D"), LoadColumn(202)]
        public string PH02D { get; set; }


        [ColumnName("PH02E"), LoadColumn(203)]
        public string PH02E { get; set; }


        [ColumnName("PH02F"), LoadColumn(204)]
        public string PH02F { get; set; }


        [ColumnName("PH03A"), LoadColumn(205)]
        public string PH03A { get; set; }


        [ColumnName("PH03B"), LoadColumn(206)]
        public string PH03B { get; set; }


        [ColumnName("PH04"), LoadColumn(207)]
        public string PH04 { get; set; }


        [ColumnName("PH05"), LoadColumn(208)]
        public string PH05 { get; set; }


        [ColumnName("PH06A"), LoadColumn(209)]
        public string PH06A { get; set; }


        [ColumnName("PH06B"), LoadColumn(210)]
        public float PH06B { get; set; }


        [ColumnName("PH06C"), LoadColumn(211)]
        public float PH06C { get; set; }


        [ColumnName("PH06D"), LoadColumn(212)]
        public string PH06D { get; set; }


        [ColumnName("PH06E"), LoadColumn(213)]
        public string PH06E { get; set; }


        [ColumnName("PH07A"), LoadColumn(214)]
        public string PH07A { get; set; }


        [ColumnName("PH07B"), LoadColumn(215)]
        public float PH07B { get; set; }


        [ColumnName("PH08"), LoadColumn(216)]
        public string PH08 { get; set; }


        [ColumnName("PH09A"), LoadColumn(217)]
        public string PH09A { get; set; }


        [ColumnName("PH09B"), LoadColumn(218)]
        public float PH09B { get; set; }


        [ColumnName("PH09C"), LoadColumn(219)]
        public float PH09C { get; set; }


        [ColumnName("PH10A"), LoadColumn(220)]
        public string PH10A { get; set; }


        [ColumnName("PH10B"), LoadColumn(221)]
        public float PH10B { get; set; }


        [ColumnName("PH11A"), LoadColumn(222)]
        public string PH11A { get; set; }


        [ColumnName("PH11B"), LoadColumn(223)]
        public string PH11B { get; set; }


        [ColumnName("PH12"), LoadColumn(224)]
        public string PH12 { get; set; }


        [ColumnName("PH13A"), LoadColumn(225)]
        public string PH13A { get; set; }


        [ColumnName("PH13B"), LoadColumn(226)]
        public float PH13B { get; set; }


        [ColumnName("PH13C"), LoadColumn(227)]
        public float PH13C { get; set; }


        [ColumnName("PH14A"), LoadColumn(228)]
        public string PH14A { get; set; }


        [ColumnName("PH14B"), LoadColumn(229)]
        public string PH14B { get; set; }


        [ColumnName("PH14C"), LoadColumn(230)]
        public string PH14C { get; set; }


        [ColumnName("PH14D"), LoadColumn(231)]
        public string PH14D { get; set; }


        [ColumnName("PH14E"), LoadColumn(232)]
        public string PH14E { get; set; }


        [ColumnName("PH14F"), LoadColumn(233)]
        public string PH14F { get; set; }


        [ColumnName("PH14G"), LoadColumn(234)]
        public string PH14G { get; set; }


        [ColumnName("PH14H"), LoadColumn(235)]
        public string PH14H { get; set; }


        [ColumnName("PH15A1"), LoadColumn(236)]
        public string PH15A1 { get; set; }


        [ColumnName("PH15A2"), LoadColumn(237)]
        public string PH15A2 { get; set; }


        [ColumnName("PH15B1"), LoadColumn(238)]
        public string PH15B1 { get; set; }


        [ColumnName("PH15B2"), LoadColumn(239)]
        public string PH15B2 { get; set; }


        [ColumnName("PH15C1"), LoadColumn(240)]
        public string PH15C1 { get; set; }


        [ColumnName("PH15C2"), LoadColumn(241)]
        public string PH15C2 { get; set; }


        [ColumnName("PH15D1"), LoadColumn(242)]
        public string PH15D1 { get; set; }


        [ColumnName("PH15D2"), LoadColumn(243)]
        public string PH15D2 { get; set; }


        [ColumnName("PH15E1"), LoadColumn(244)]
        public string PH15E1 { get; set; }


        [ColumnName("PH15E2"), LoadColumn(245)]
        public string PH15E2 { get; set; }


        [ColumnName("PH16"), LoadColumn(246)]
        public string PH16 { get; set; }


        [ColumnName("PH17"), LoadColumn(247)]
        public float PH17 { get; set; }


        [ColumnName("PH18"), LoadColumn(248)]
        public float PH18 { get; set; }


        [ColumnName("PH19"), LoadColumn(249)]
        public float PH19 { get; set; }


        [ColumnName("PH20"), LoadColumn(250)]
        public float PH20 { get; set; }


        [ColumnName("PH21"), LoadColumn(251)]
        public float PH21 { get; set; }


        [ColumnName("PH22"), LoadColumn(252)]
        public float PH22 { get; set; }


        [ColumnName("PH23"), LoadColumn(253)]
        public float PH23 { get; set; }


        [ColumnName("PH24"), LoadColumn(254)]
        public float PH24 { get; set; }


        [ColumnName("PH25"), LoadColumn(255)]
        public string PH25 { get; set; }


        [ColumnName("PH26"), LoadColumn(256)]
        public float PH26 { get; set; }


        [ColumnName("PH27"), LoadColumn(257)]
        public string PH27 { get; set; }


        [ColumnName("PH28"), LoadColumn(258)]
        public float PH28 { get; set; }


        [ColumnName("PH29"), LoadColumn(259)]
        public float PH29 { get; set; }


        [ColumnName("PH30"), LoadColumn(260)]
        public float PH30 { get; set; }


        [ColumnName("PH31A"), LoadColumn(261)]
        public string PH31A { get; set; }


        [ColumnName("PH31B"), LoadColumn(262)]
        public string PH31B { get; set; }


        [ColumnName("PH31C"), LoadColumn(263)]
        public string PH31C { get; set; }


        [ColumnName("PH32A"), LoadColumn(264)]
        public string PH32A { get; set; }


        [ColumnName("PH32B"), LoadColumn(265)]
        public string PH32B { get; set; }


        [ColumnName("PH32C"), LoadColumn(266)]
        public string PH32C { get; set; }


        [ColumnName("PH33"), LoadColumn(267)]
        public string PH33 { get; set; }


        [ColumnName("PH34A"), LoadColumn(268)]
        public string PH34A { get; set; }


        [ColumnName("PH34B"), LoadColumn(269)]
        public string PH34B { get; set; }


        [ColumnName("PH34C"), LoadColumn(270)]
        public string PH34C { get; set; }


        [ColumnName("PH34D"), LoadColumn(271)]
        public string PH34D { get; set; }


        [ColumnName("PH34E"), LoadColumn(272)]
        public string PH34E { get; set; }


        [ColumnName("PH35A"), LoadColumn(273)]
        public string PH35A { get; set; }


        [ColumnName("PH35B"), LoadColumn(274)]
        public string PH35B { get; set; }


        [ColumnName("PH35C"), LoadColumn(275)]
        public string PH35C { get; set; }


        [ColumnName("PH35D"), LoadColumn(276)]
        public string PH35D { get; set; }


        [ColumnName("PE01"), LoadColumn(277)]
        public string PE01 { get; set; }


        [ColumnName("PE02"), LoadColumn(278)]
        public string PE02 { get; set; }


        [ColumnName("PE03A"), LoadColumn(279)]
        public string PE03A { get; set; }


        [ColumnName("PE03B"), LoadColumn(280)]
        public string PE03B { get; set; }


        [ColumnName("PE03C"), LoadColumn(281)]
        public string PE03C { get; set; }


        [ColumnName("PE03D"), LoadColumn(282)]
        public string PE03D { get; set; }


        [ColumnName("PE04A"), LoadColumn(283)]
        public string PE04A { get; set; }


        [ColumnName("PE04B"), LoadColumn(284)]
        public float PE04B { get; set; }


        [ColumnName("PE05A"), LoadColumn(285)]
        public string PE05A { get; set; }


        [ColumnName("PE05B"), LoadColumn(286)]
        public float PE05B { get; set; }


        [ColumnName("PE06A"), LoadColumn(287)]
        public string PE06A { get; set; }


        [ColumnName("PE06B"), LoadColumn(288)]
        public float PE06B { get; set; }


        [ColumnName("PE07A"), LoadColumn(289)]
        public string PE07A { get; set; }


        [ColumnName("PE07B"), LoadColumn(290)]
        public float PE07B { get; set; }


        [ColumnName("PE08A"), LoadColumn(291)]
        public string PE08A { get; set; }


        [ColumnName("PE08B"), LoadColumn(292)]
        public float PE08B { get; set; }


        [ColumnName("PE09A"), LoadColumn(293)]
        public string PE09A { get; set; }


        [ColumnName("PE09B"), LoadColumn(294)]
        public float PE09B { get; set; }


        [ColumnName("PE10A"), LoadColumn(295)]
        public string PE10A { get; set; }


        [ColumnName("PE10B"), LoadColumn(296)]
        public float PE10B { get; set; }


        [ColumnName("PE11A"), LoadColumn(297)]
        public string PE11A { get; set; }


        [ColumnName("PE11B"), LoadColumn(298)]
        public float PE11B { get; set; }


        [ColumnName("PE12A"), LoadColumn(299)]
        public string PE12A { get; set; }


        [ColumnName("PE12B"), LoadColumn(300)]
        public float PE12B { get; set; }


        [ColumnName("PE13"), LoadColumn(301)]
        public string PE13 { get; set; }


        [ColumnName("PE14"), LoadColumn(302)]
        public string PE14 { get; set; }


        [ColumnName("PE15"), LoadColumn(303)]
        public string PE15 { get; set; }


        [ColumnName("PE16"), LoadColumn(304)]
        public string PE16 { get; set; }


        [ColumnName("PE17"), LoadColumn(305)]
        public string PE17 { get; set; }


        [ColumnName("PE18"), LoadColumn(306)]
        public string PE18 { get; set; }


        [ColumnName("PE19"), LoadColumn(307)]
        public string PE19 { get; set; }


        [ColumnName("PE20"), LoadColumn(308)]
        public string PE20 { get; set; }


        [ColumnName("PE21"), LoadColumn(309)]
        public string PE21 { get; set; }


        [ColumnName("PE22A"), LoadColumn(310)]
        public string PE22A { get; set; }


        [ColumnName("PE22B"), LoadColumn(311)]
        public string PE22B { get; set; }


        [ColumnName("PE22C"), LoadColumn(312)]
        public string PE22C { get; set; }


        [ColumnName("PE22D"), LoadColumn(313)]
        public string PE22D { get; set; }


        [ColumnName("PE23A"), LoadColumn(314)]
        public string PE23A { get; set; }


        [ColumnName("PE23B"), LoadColumn(315)]
        public float PE23B { get; set; }


        [ColumnName("PE24"), LoadColumn(316)]
        public string PE24 { get; set; }


        [ColumnName("PE25A"), LoadColumn(317)]
        public string PE25A { get; set; }


        [ColumnName("PE25B"), LoadColumn(318)]
        public string PE25B { get; set; }


        [ColumnName("PE26A"), LoadColumn(319)]
        public string PE26A { get; set; }


        [ColumnName("PE26B"), LoadColumn(320)]
        public string PE26B { get; set; }


        [ColumnName("PE26C"), LoadColumn(321)]
        public string PE26C { get; set; }


        [ColumnName("PE26D"), LoadColumn(322)]
        public string PE26D { get; set; }


        [ColumnName("PE26E"), LoadColumn(323)]
        public string PE26E { get; set; }


        [ColumnName("PE26F"), LoadColumn(324)]
        public string PE26F { get; set; }


        [ColumnName("PE26G"), LoadColumn(325)]
        public string PE26G { get; set; }


        [ColumnName("PE27"), LoadColumn(326)]
        public string PE27 { get; set; }


        [ColumnName("PE28A"), LoadColumn(327)]
        public float PE28A { get; set; }


        [ColumnName("PE28B"), LoadColumn(328)]
        public float PE28B { get; set; }


        [ColumnName("PE29"), LoadColumn(329)]
        public string PE29 { get; set; }


        [ColumnName("PE30"), LoadColumn(330)]
        public string PE30 { get; set; }


        [ColumnName("PE31A"), LoadColumn(331)]
        public float PE31A { get; set; }


        [ColumnName("PE31B"), LoadColumn(332)]
        public float PE31B { get; set; }


        [ColumnName("PE32"), LoadColumn(333)]
        public string PE32 { get; set; }


        [ColumnName("PE33A"), LoadColumn(334)]
        public string PE33A { get; set; }


        [ColumnName("PE33BD"), LoadColumn(335)]
        public string PE33BD { get; set; }


        [ColumnName("PE33B"), LoadColumn(336)]
        public float PE33B { get; set; }


        [ColumnName("PE34A"), LoadColumn(337)]
        public float PE34A { get; set; }


        [ColumnName("PE34B"), LoadColumn(338)]
        public float PE34B { get; set; }


        [ColumnName("PE35A"), LoadColumn(339)]
        public string PE35A { get; set; }


        [ColumnName("PE35B"), LoadColumn(340)]
        public float PE35B { get; set; }


        [ColumnName("PE36"), LoadColumn(341)]
        public string PE36 { get; set; }


        [ColumnName("PE37"), LoadColumn(342)]
        public string PE37 { get; set; }


        [ColumnName("PE38A"), LoadColumn(343)]
        public string PE38A { get; set; }


        [ColumnName("PE38B"), LoadColumn(344)]
        public float PE38B { get; set; }


        [ColumnName("PE39A"), LoadColumn(345)]
        public string PE39A { get; set; }


        [ColumnName("PE39B"), LoadColumn(346)]
        public float PE39B { get; set; }


        [ColumnName("PE40A"), LoadColumn(347)]
        public string PE40A { get; set; }


        [ColumnName("PE40B"), LoadColumn(348)]
        public float PE40B { get; set; }


        [ColumnName("PE41A"), LoadColumn(349)]
        public string PE41A { get; set; }


        [ColumnName("PE41B"), LoadColumn(350)]
        public float PE41B { get; set; }


        [ColumnName("PE42A"), LoadColumn(351)]
        public string PE42A { get; set; }


        [ColumnName("PE42B"), LoadColumn(352)]
        public float PE42B { get; set; }


        [ColumnName("PE43A"), LoadColumn(353)]
        public string PE43A { get; set; }


        [ColumnName("PE43B"), LoadColumn(354)]
        public float PE43B { get; set; }


        [ColumnName("PE44A"), LoadColumn(355)]
        public string PE44A { get; set; }


        [ColumnName("PE44B"), LoadColumn(356)]
        public float PE44B { get; set; }


        [ColumnName("PE45A"), LoadColumn(357)]
        public string PE45A { get; set; }


        [ColumnName("PE45B"), LoadColumn(358)]
        public float PE45B { get; set; }


        [ColumnName("PE46"), LoadColumn(359)]
        public string PE46 { get; set; }


        [ColumnName("PE47"), LoadColumn(360)]
        public string PE47 { get; set; }


        [ColumnName("PE48"), LoadColumn(361)]
        public float PE48 { get; set; }


        [ColumnName("PE49"), LoadColumn(362)]
        public string PE49 { get; set; }


        [ColumnName("PE50"), LoadColumn(363)]
        public string PE50 { get; set; }


        [ColumnName("PE51"), LoadColumn(364)]
        public string PE51 { get; set; }


        [ColumnName("PE52A"), LoadColumn(365)]
        public string PE52A { get; set; }


        [ColumnName("PE52B"), LoadColumn(366)]
        public float PE52B { get; set; }


        [ColumnName("PE53"), LoadColumn(367)]
        public string PE53 { get; set; }


        [ColumnName("PE54"), LoadColumn(368)]
        public string PE54 { get; set; }


        [ColumnName("PE55"), LoadColumn(369)]
        public float PE55 { get; set; }


        [ColumnName("PE56"), LoadColumn(370)]
        public string PE56 { get; set; }


        [ColumnName("PE57"), LoadColumn(371)]
        public string PE57 { get; set; }


        [ColumnName("PE58"), LoadColumn(372)]
        public string PE58 { get; set; }


        [ColumnName("PE59A"), LoadColumn(373)]
        public string PE59A { get; set; }


        [ColumnName("PE59B"), LoadColumn(374)]
        public float PE59B { get; set; }


        [ColumnName("PM01A"), LoadColumn(375)]
        public string PM01A { get; set; }


        [ColumnName("PM01BD"), LoadColumn(376)]
        public string PM01BD { get; set; }


        [ColumnName("PM01B"), LoadColumn(377)]
        public string PM01B { get; set; }


        [ColumnName("PM02"), LoadColumn(378)]
        public string PM02 { get; set; }


        [ColumnName("PM03A"), LoadColumn(379)]
        public string PM03A { get; set; }


        [ColumnName("PM03BD"), LoadColumn(380)]
        public string PM03BD { get; set; }


        [ColumnName("PM03B"), LoadColumn(381)]
        public string PM03B { get; set; }


        [ColumnName("PM04"), LoadColumn(382)]
        public string PM04 { get; set; }


        [ColumnName("PA01"), LoadColumn(383)]
        public string PA01 { get; set; }


        [ColumnName("PA02"), LoadColumn(384)]
        public string PA02 { get; set; }


        [ColumnName("PA03"), LoadColumn(385)]
        public string PA03 { get; set; }


        [ColumnName("PA04"), LoadColumn(386)]
        public string PA04 { get; set; }


        [ColumnName("PA05"), LoadColumn(387)]
        public string PA05 { get; set; }


        [ColumnName("PA06"), LoadColumn(388)]
        public float PA06 { get; set; }


        [ColumnName("PA07"), LoadColumn(389)]
        public string PA07 { get; set; }


        [ColumnName("PA08"), LoadColumn(390)]
        public string PA08 { get; set; }


        [ColumnName("PA09"), LoadColumn(391)]
        public string PA09 { get; set; }


        [ColumnName("PA10"), LoadColumn(392)]
        public string PA10 { get; set; }


        [ColumnName("PA11"), LoadColumn(393)]
        public string PA11 { get; set; }


        [ColumnName("PA12"), LoadColumn(394)]
        public string PA12 { get; set; }


        [ColumnName("PA13"), LoadColumn(395)]
        public float PA13 { get; set; }


        [ColumnName("PA14"), LoadColumn(396)]
        public string PA14 { get; set; }


        [ColumnName("PA15D1"), LoadColumn(397)]
        public string PA15D1 { get; set; }


        [ColumnName("PA15D2"), LoadColumn(398)]
        public string PA15D2 { get; set; }


        [ColumnName("PA15"), LoadColumn(399)]
        public float PA15 { get; set; }


        [ColumnName("PA16D1"), LoadColumn(400)]
        public string PA16D1 { get; set; }


        [ColumnName("PA16D2"), LoadColumn(401)]
        public string PA16D2 { get; set; }


        [ColumnName("PA16"), LoadColumn(402)]
        public float PA16 { get; set; }


        [ColumnName("PA17A"), LoadColumn(403)]
        public string PA17A { get; set; }


        [ColumnName("PA17B"), LoadColumn(404)]
        public string PA17B { get; set; }


        [ColumnName("PA18"), LoadColumn(405)]
        public string PA18 { get; set; }


        [ColumnName("PA19"), LoadColumn(406)]
        public float PA19 { get; set; }


        [ColumnName("PA20"), LoadColumn(407)]
        public float PA20 { get; set; }


        [ColumnName("PA21A"), LoadColumn(408)]
        public string PA21A { get; set; }


        [ColumnName("PA21B"), LoadColumn(409)]
        public float PA21B { get; set; }


        [ColumnName("PA22"), LoadColumn(410)]
        public string PA22 { get; set; }


        [ColumnName("PA23A"), LoadColumn(411)]
        public string PA23A { get; set; }


        [ColumnName("PA23B"), LoadColumn(412)]
        public string PA23B { get; set; }


        [ColumnName("PA24A"), LoadColumn(413)]
        public string PA24A { get; set; }


        [ColumnName("PA24B"), LoadColumn(414)]
        public string PA24B { get; set; }


        [ColumnName("PA25A"), LoadColumn(415)]
        public string PA25A { get; set; }


        [ColumnName("PA25B"), LoadColumn(416)]
        public string PA25B { get; set; }


        [ColumnName("PA26"), LoadColumn(417)]
        public string PA26 { get; set; }


        [ColumnName("PA27A"), LoadColumn(418)]
        public string PA27A { get; set; }


        [ColumnName("PA27B"), LoadColumn(419)]
        public float PA27B { get; set; }


        [ColumnName("PA28"), LoadColumn(420)]
        public string PA28 { get; set; }


        [ColumnName("PA29"), LoadColumn(421)]
        public string PA29 { get; set; }


        [ColumnName("PA30A"), LoadColumn(422)]
        public string PA30A { get; set; }


        [ColumnName("PA30B"), LoadColumn(423)]
        public float PA30B { get; set; }


        [ColumnName("PA31A"), LoadColumn(424)]
        public string PA31A { get; set; }


        [ColumnName("PA31B"), LoadColumn(425)]
        public string PA31B { get; set; }


        [ColumnName("PA32"), LoadColumn(426)]
        public string PA32 { get; set; }


        [ColumnName("PA33A1"), LoadColumn(427)]
        public string PA33A1 { get; set; }


        [ColumnName("PA33A2"), LoadColumn(428)]
        public float PA33A2 { get; set; }


        [ColumnName("PA33B1"), LoadColumn(429)]
        public string PA33B1 { get; set; }


        [ColumnName("PA33B2"), LoadColumn(430)]
        public float PA33B2 { get; set; }


        [ColumnName("PA33C1"), LoadColumn(431)]
        public string PA33C1 { get; set; }


        [ColumnName("PA33C2"), LoadColumn(432)]
        public float PA33C2 { get; set; }


        [ColumnName("PA34A"), LoadColumn(433)]
        public string PA34A { get; set; }


        [ColumnName("PA34B"), LoadColumn(434)]
        public string PA34B { get; set; }


        [ColumnName("PA35A"), LoadColumn(435)]
        public string PA35A { get; set; }


        [ColumnName("PA35B"), LoadColumn(436)]
        public float PA35B { get; set; }


        [ColumnName("PA36A"), LoadColumn(437)]
        public string PA36A { get; set; }


        [ColumnName("PA36B"), LoadColumn(438)]
        public string PA36B { get; set; }


        [ColumnName("PA37"), LoadColumn(439)]
        public float PA37 { get; set; }


        [ColumnName("PA38A"), LoadColumn(440)]
        public string PA38A { get; set; }


        [ColumnName("PA38B"), LoadColumn(441)]
        public string PA38B { get; set; }


        [ColumnName("PA39A"), LoadColumn(442)]
        public string PA39A { get; set; }


        [ColumnName("PA39B"), LoadColumn(443)]
        public string PA39B { get; set; }


        [ColumnName("PA40A"), LoadColumn(444)]
        public string PA40A { get; set; }


        [ColumnName("PA40B"), LoadColumn(445)]
        public float PA40B { get; set; }


        [ColumnName("PA41A"), LoadColumn(446)]
        public string PA41A { get; set; }


        [ColumnName("PA41B"), LoadColumn(447)]
        public string PA41B { get; set; }


        [ColumnName("PA42A"), LoadColumn(448)]
        public string PA42A { get; set; }


        [ColumnName("PA42B"), LoadColumn(449)]
        public float PA42B { get; set; }


        [ColumnName("PA43A"), LoadColumn(450)]
        public string PA43A { get; set; }


        [ColumnName("PA43B"), LoadColumn(451)]
        public float PA43B { get; set; }


        [ColumnName("PA43C"), LoadColumn(452)]
        public string PA43C { get; set; }


        [ColumnName("PA44A"), LoadColumn(453)]
        public string PA44A { get; set; }


        [ColumnName("PA44B"), LoadColumn(454)]
        public float PA44B { get; set; }


        [ColumnName("PA45A"), LoadColumn(455)]
        public string PA45A { get; set; }


        [ColumnName("PA45B"), LoadColumn(456)]
        public float PA45B { get; set; }


        [ColumnName("PA45C"), LoadColumn(457)]
        public float PA45C { get; set; }


        [ColumnName("PA46A"), LoadColumn(458)]
        public string PA46A { get; set; }


        [ColumnName("PA46B"), LoadColumn(459)]
        public float PA46B { get; set; }


        [ColumnName("PA47"), LoadColumn(460)]
        public string PA47 { get; set; }


        [ColumnName("PA48A"), LoadColumn(461)]
        public string PA48A { get; set; }


        [ColumnName("PA48BD"), LoadColumn(462)]
        public string PA48BD { get; set; }


        [ColumnName("PA48B"), LoadColumn(463)]
        public float PA48B { get; set; }


        [ColumnName("PA49A"), LoadColumn(464)]
        public string PA49A { get; set; }


        [ColumnName("PA49B"), LoadColumn(465)]
        public float PA49B { get; set; }


        [ColumnName("PA50A"), LoadColumn(466)]
        public float PA50A { get; set; }


        [ColumnName("PA50B"), LoadColumn(467)]
        public float PA50B { get; set; }


        [ColumnName("PA51"), LoadColumn(468)]
        public string PA51 { get; set; }


        [ColumnName("PA52"), LoadColumn(469)]
        public string PA52 { get; set; }


        [ColumnName("PA53A"), LoadColumn(470)]
        public string PA53A { get; set; }


        [ColumnName("PA53B"), LoadColumn(471)]
        public string PA53B { get; set; }


        [ColumnName("PA53C"), LoadColumn(472)]
        public string PA53C { get; set; }


        [ColumnName("PA54A"), LoadColumn(473)]
        public string PA54A { get; set; }


        [ColumnName("PA54B"), LoadColumn(474)]
        public float PA54B { get; set; }


        [ColumnName("PA55D1"), LoadColumn(475)]
        public string PA55D1 { get; set; }


        [ColumnName("PA55D2"), LoadColumn(476)]
        public string PA55D2 { get; set; }


        [ColumnName("PA55"), LoadColumn(477)]
        public float PA55 { get; set; }


        [ColumnName("PA56D1"), LoadColumn(478)]
        public string PA56D1 { get; set; }


        [ColumnName("PA56D2"), LoadColumn(479)]
        public string PA56D2 { get; set; }


        [ColumnName("PA56"), LoadColumn(480)]
        public float PA56 { get; set; }


        [ColumnName("PA57A"), LoadColumn(481)]
        public string PA57A { get; set; }


        [ColumnName("PA57B"), LoadColumn(482)]
        public string PA57B { get; set; }


        [ColumnName("PA58"), LoadColumn(483)]
        public string PA58 { get; set; }


        [ColumnName("PA59"), LoadColumn(484)]
        public float PA59 { get; set; }


        [ColumnName("PA60"), LoadColumn(485)]
        public float PA60 { get; set; }


        [ColumnName("PA61A"), LoadColumn(486)]
        public string PA61A { get; set; }


        [ColumnName("PA61B"), LoadColumn(487)]
        public float PA61B { get; set; }


        [ColumnName("PA62"), LoadColumn(488)]
        public string PA62 { get; set; }


        [ColumnName("PA63A"), LoadColumn(489)]
        public string PA63A { get; set; }


        [ColumnName("PA63B"), LoadColumn(490)]
        public string PA63B { get; set; }


        [ColumnName("PA64A"), LoadColumn(491)]
        public string PA64A { get; set; }


        [ColumnName("PA64B"), LoadColumn(492)]
        public string PA64B { get; set; }


        [ColumnName("PA65A"), LoadColumn(493)]
        public float PA65A { get; set; }


        [ColumnName("PA65B"), LoadColumn(494)]
        public string PA65B { get; set; }


        [ColumnName("PA66"), LoadColumn(495)]
        public float PA66 { get; set; }


        [ColumnName("PA67A"), LoadColumn(496)]
        public string PA67A { get; set; }


        [ColumnName("PA67B"), LoadColumn(497)]
        public float PA67B { get; set; }


        [ColumnName("PA68A"), LoadColumn(498)]
        public string PA68A { get; set; }


        [ColumnName("PA68B"), LoadColumn(499)]
        public float PA68B { get; set; }


        [ColumnName("PA69A"), LoadColumn(500)]
        public string PA69A { get; set; }


        [ColumnName("PA69B"), LoadColumn(501)]
        public float PA69B { get; set; }


        [ColumnName("PA70A"), LoadColumn(502)]
        public string PA70A { get; set; }


        [ColumnName("PA70B"), LoadColumn(503)]
        public float PA70B { get; set; }


        [ColumnName("PA71A"), LoadColumn(504)]
        public string PA71A { get; set; }


        [ColumnName("PA71B"), LoadColumn(505)]
        public float PA71B { get; set; }


        [ColumnName("PA72"), LoadColumn(506)]
        public string PA72 { get; set; }


        [ColumnName("PA73"), LoadColumn(507)]
        public float PA73 { get; set; }


        [ColumnName("PA74"), LoadColumn(508)]
        public string PA74 { get; set; }


        [ColumnName("PA75A"), LoadColumn(509)]
        public string PA75A { get; set; }


        [ColumnName("PA75B"), LoadColumn(510)]
        public float PA75B { get; set; }


        [ColumnName("PA76"), LoadColumn(511)]
        public string PA76 { get; set; }


        [ColumnName("PA77"), LoadColumn(512)]
        public string PA77 { get; set; }


        [ColumnName("PA78A"), LoadColumn(513)]
        public float PA78A { get; set; }


        [ColumnName("PA78B"), LoadColumn(514)]
        public string PA78B { get; set; }


        [ColumnName("PA79"), LoadColumn(515)]
        public string PA79 { get; set; }


        [ColumnName("PA80A"), LoadColumn(516)]
        public string PA80A { get; set; }


        [ColumnName("PA80B"), LoadColumn(517)]
        public float PA80B { get; set; }


        [ColumnName("PA80C"), LoadColumn(518)]
        public string PA80C { get; set; }


        [ColumnName("PA81A"), LoadColumn(519)]
        public string PA81A { get; set; }


        [ColumnName("PA81B"), LoadColumn(520)]
        public float PA81B { get; set; }


        [ColumnName("PA81C"), LoadColumn(521)]
        public string PA81C { get; set; }


        [ColumnName("PA82"), LoadColumn(522)]
        public string PA82 { get; set; }


        [ColumnName("PA83"), LoadColumn(523)]
        public string PA83 { get; set; }


        [ColumnName("PA84"), LoadColumn(524)]
        public string PA84 { get; set; }


        [ColumnName("PA85A"), LoadColumn(525)]
        public string PA85A { get; set; }


        [ColumnName("PA85B"), LoadColumn(526)]
        public float PA85B { get; set; }


        [ColumnName("PA85C"), LoadColumn(527)]
        public string PA85C { get; set; }


        [ColumnName("PA86"), LoadColumn(528)]
        public string PA86 { get; set; }


        [ColumnName("PA87A"), LoadColumn(529)]
        public string PA87A { get; set; }


        [ColumnName("PA87B"), LoadColumn(530)]
        public string PA87B { get; set; }


        [ColumnName("PA88"), LoadColumn(531)]
        public string PA88 { get; set; }


        [ColumnName("PA89"), LoadColumn(532)]
        public string PA89 { get; set; }


        [ColumnName("PA90"), LoadColumn(533)]
        public string PA90 { get; set; }


        [ColumnName("PA91"), LoadColumn(534)]
        public string PA91 { get; set; }


        [ColumnName("PA92"), LoadColumn(535)]
        public float PA92 { get; set; }


        [ColumnName("PA93"), LoadColumn(536)]
        public string PA93 { get; set; }


        [ColumnName("PA94A"), LoadColumn(537)]
        public string PA94A { get; set; }


        [ColumnName("PA94B"), LoadColumn(538)]
        public float PA94B { get; set; }


        [ColumnName("PA95"), LoadColumn(539)]
        public string PA95 { get; set; }


        [ColumnName("PA96A"), LoadColumn(540)]
        public string PA96A { get; set; }


        [ColumnName("PA96B"), LoadColumn(541)]
        public string PA96B { get; set; }


        [ColumnName("PA97"), LoadColumn(542)]
        public string PA97 { get; set; }


        [ColumnName("PF01"), LoadColumn(543)]
        public string PF01 { get; set; }


        [ColumnName("PF02A"), LoadColumn(544)]
        public string PF02A { get; set; }


        [ColumnName("PF02B"), LoadColumn(545)]
        public string PF02B { get; set; }


        [ColumnName("PF03"), LoadColumn(546)]
        public string PF03 { get; set; }


        [ColumnName("PF04"), LoadColumn(547)]
        public string PF04 { get; set; }


        [ColumnName("PF05"), LoadColumn(548)]
        public string PF05 { get; set; }


        [ColumnName("PF06A"), LoadColumn(549)]
        public string PF06A { get; set; }


        [ColumnName("PF06B"), LoadColumn(550)]
        public float PF06B { get; set; }


        [ColumnName("PF07A"), LoadColumn(551)]
        public string PF07A { get; set; }


        [ColumnName("PF07B"), LoadColumn(552)]
        public float PF07B { get; set; }


        [ColumnName("PF08"), LoadColumn(553)]
        public string PF08 { get; set; }


        [ColumnName("PF09"), LoadColumn(554)]
        public string PF09 { get; set; }


        [ColumnName("PF10"), LoadColumn(555)]
        public string PF10 { get; set; }


        [ColumnName("PF11"), LoadColumn(556)]
        public string PF11 { get; set; }


        [ColumnName("PF12"), LoadColumn(557)]
        public string PF12 { get; set; }


        [ColumnName("PF13A"), LoadColumn(558)]
        public string PF13A { get; set; }


        [ColumnName("PF13B"), LoadColumn(559)]
        public string PF13B { get; set; }


        [ColumnName("PF14"), LoadColumn(560)]
        public string PF14 { get; set; }


        [ColumnName("PF15"), LoadColumn(561)]
        public string PF15 { get; set; }


        [ColumnName("PF16"), LoadColumn(562)]
        public float PF16 { get; set; }


        [ColumnName("PF17"), LoadColumn(563)]
        public string PF17 { get; set; }


        [ColumnName("PF18A"), LoadColumn(564)]
        public float PF18A { get; set; }


        [ColumnName("PF18B"), LoadColumn(565)]
        public float PF18B { get; set; }


        [ColumnName("PF19"), LoadColumn(566)]
        public string PF19 { get; set; }


        [ColumnName("PF20A"), LoadColumn(567)]
        public float PF20A { get; set; }


        [ColumnName("PF20B"), LoadColumn(568)]
        public float PF20B { get; set; }


        [ColumnName("PF20C"), LoadColumn(569)]
        public float PF20C { get; set; }


        [ColumnName("PF21"), LoadColumn(570)]
        public string PF21 { get; set; }


        [ColumnName("PF22"), LoadColumn(571)]
        public string PF22 { get; set; }


        [ColumnName("PF23"), LoadColumn(572)]
        public string PF23 { get; set; }


        [ColumnName("PF24"), LoadColumn(573)]
        public string PF24 { get; set; }


        [ColumnName("PF25A"), LoadColumn(574)]
        public string PF25A { get; set; }


        [ColumnName("PF25B"), LoadColumn(575)]
        public string PF25B { get; set; }


        [ColumnName("PF26"), LoadColumn(576)]
        public string PF26 { get; set; }


        [ColumnName("PF27"), LoadColumn(577)]
        public string PF27 { get; set; }


        [ColumnName("PF28"), LoadColumn(578)]
        public string PF28 { get; set; }


        [ColumnName("PF29"), LoadColumn(579)]
        public string PF29 { get; set; }


        [ColumnName("PF30A"), LoadColumn(580)]
        public string PF30A { get; set; }


        [ColumnName("PF30B"), LoadColumn(581)]
        public string PF30B { get; set; }


        [ColumnName("PF31"), LoadColumn(582)]
        public string PF31 { get; set; }


        [ColumnName("PF32A"), LoadColumn(583)]
        public float PF32A { get; set; }


        [ColumnName("PF32B"), LoadColumn(584)]
        public string PF32B { get; set; }


        [ColumnName("PF33"), LoadColumn(585)]
        public string PF33 { get; set; }


        [ColumnName("PF34A"), LoadColumn(586)]
        public float PF34A { get; set; }


        [ColumnName("PF34B"), LoadColumn(587)]
        public string PF34B { get; set; }


        [ColumnName("PF35A"), LoadColumn(588)]
        public string PF35A { get; set; }


        [ColumnName("PF35B"), LoadColumn(589)]
        public float PF35B { get; set; }


        [ColumnName("PF35C"), LoadColumn(590)]
        public string PF35C { get; set; }


        [ColumnName("PF36"), LoadColumn(591)]
        public string PF36 { get; set; }


        [ColumnName("PF37"), LoadColumn(592)]
        public string PF37 { get; set; }


        [ColumnName("PF38A"), LoadColumn(593)]
        public string PF38A { get; set; }


        [ColumnName("PF38B"), LoadColumn(594)]
        public string PF38B { get; set; }


        [ColumnName("PF38C"), LoadColumn(595)]
        public string PF38C { get; set; }


        [ColumnName("PG01A"), LoadColumn(596)]
        public string PG01A { get; set; }


        [ColumnName("PG01B"), LoadColumn(597)]
        public float PG01B { get; set; }


        [ColumnName("PG02A"), LoadColumn(598)]
        public string PG02A { get; set; }


        [ColumnName("PG02B"), LoadColumn(599)]
        public float PG02B { get; set; }


        [ColumnName("PG03A"), LoadColumn(600)]
        public string PG03A { get; set; }


        [ColumnName("PG03B"), LoadColumn(601)]
        public float PG03B { get; set; }


        [ColumnName("PG04A"), LoadColumn(602)]
        public string PG04A { get; set; }


        [ColumnName("PG04B"), LoadColumn(603)]
        public float PG04B { get; set; }


        [ColumnName("PG05A"), LoadColumn(604)]
        public string PG05A { get; set; }


        [ColumnName("PG05B"), LoadColumn(605)]
        public float PG05B { get; set; }


        [ColumnName("PG06A"), LoadColumn(606)]
        public string PG06A { get; set; }


        [ColumnName("PG06B"), LoadColumn(607)]
        public float PG06B { get; set; }


        [ColumnName("PG07A"), LoadColumn(608)]
        public string PG07A { get; set; }


        [ColumnName("PG07B"), LoadColumn(609)]
        public float PG07B { get; set; }


        [ColumnName("PG08A"), LoadColumn(610)]
        public string PG08A { get; set; }


        [ColumnName("PG08B"), LoadColumn(611)]
        public float PG08B { get; set; }


        [ColumnName("PCOMP"), LoadColumn(612)]
        public string PCOMP { get; set; }


        [ColumnName("FEXP"), LoadColumn(613)]
        public float FEXP { get; set; }


        [ColumnName("REGIONAL"), LoadColumn(614)]
        public string REGIONAL { get; set; }


        [ColumnName("FASE"), LoadColumn(615)]
        public string FASE { get; set; }


    }
}
